name: Cross (Musl)

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        cross: [arm-linux-musleabi, aarch64-linux-musl]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - name: Installation
        run: |
          wget https://musl.cc/${{ matrix.cross }}-cross.tgz
          tar -xvf ${{ matrix.cross }}-cross.tgz

      - name: Tests
        run: |
          xmake f -p cross --sdk=`pwd`/${{ matrix.cross }}-cross --syslinks="atomic"
          xmake

